service: slack-standup
frameworkVersion: '3'
provider:
  architecture: arm64
  lambdaHashingVersion: "20201221"
  name: aws
  runtime: nodejs14.x
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    stage: ${self:provider.stage}
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  memorySize: 180
  logRetentionInDays: 5
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
        - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${self:service}-${opt:stage, self:provider.stage}-*
    - Effect: "Allow"
      Action:
        - "secretsmanager:GetSecretValue"
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:secretsmanager'
            - ${self:provider.region}
            - Ref: 'AWS::AccountId'
            - 'secret'
            - 'SlackStandup-secret-*'
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:dynamodb'
            - ${self:provider.region}
            - Ref: 'AWS::AccountId'
            - 'table/*_STANDUP_STATUS'
    - Effect: Allow
      Action:
        - dynamodb:Query
      Resource:
        Fn::Join:
          - ':'
          - - 'arn:aws:dynamodb'
            - ${self:provider.region}
            - Ref: 'AWS::AccountId'
            - 'table/*_STANDUP_STATUS/index/*'
resources:
  Resources:
    StatusDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "userId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "userId"
            KeyType: "RANGE"
        GlobalSecondaryIndexes:
          - IndexName: "userId-index"
            KeySchema:
              - AttributeName: "userId"
                KeyType: "HASH"
            Projection:
              ProjectionType: "ALL"
            ProvisionedThroughput:
              ReadCapacityUnits: 2
              WriteCapacityUnits: 2
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: ${self:provider.stage}_STANDUP_STATUS
        TimeToLiveSpecification:
          AttributeName: timeToLive
          Enabled: true
functions:
  slack:
    provisionedConcurrency: 1
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post
  worker:
    provisionedConcurrency: 1
    handler: src/worker.handler
    events:
      - http:
          path: worker/events
          method: post
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-express
#  - serverless-provisioned-concurrency-autoscaling
package:
  excludeDevDependencies: true
  individually: true
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    #      forceExclude:
    #        - aws-sdk
    excludeFiles: src/**/*.test.js